### ISSUE TITLE
第二批计划清单

### ISSUE THREAD

**Issue by djyde** [stickeroverflow/sticker-requests#1]
- [x] Yarn (https://github.com/yarnpkg/assets)
- [x] npm (https://github.com/npm/logos)
- [x] Haskell (https://wiki.haskell.org/Thompson-Wheeler_logo)
- [x] JS 小尺寸
- [x] Git 小尺寸
- [x] TS 小尺寸
- [x] Node.js #8 
- [x] Golang #12 
- [x] Rust #11 
- [x] Firefox #13 
- [x] PHP #9 
- [ ] ~~Java~~ #14 
- [x] Linux #15 
- [x] Python #10 
- [x] Ruby #16 
- [x] GNU #17 
- [x] Travis #19

**Comment by jxdwinter** [comment]
+1 npm

**Comment by lukexluo** [comment]
Google Chrome

**Comment by yangsoon** [comment]
希望能有python Linux的图标

**Comment by djyde** [comment]
额，没找到 Google Chrome 图标的许可

**Comment by Cye3s** [comment]
来个Firefox 或 老式哥斯拉形像的 Mozilla  logo吧

**Comment by egoist** [comment]
看来 Google 的产品都不行了: https://www.google.com/permissions/using-the-logo.html

> We receive lots of requests from folks who want to incorporate the Google logo or Google product logos into a new T-shirt design, a toy, software packaging, or other products. Unfortunately, we cannot grant permission for these uses.

**Comment by djyde** [comment]
Java 不能印 #14

**Comment by cosmtrek** [comment]
有 kubernetes 么？[Logo Usage](https://github.com/kubernetes/kubernetes/blob/master/logo/usage_guidelines.md)

**Comment by djyde** [comment]
![image](https://user-images.githubusercontent.com/914329/31776231-91e80b2c-b4b0-11e7-9833-f07bf64167ca.png)

**Comment by djyde** [comment]
成功印刷
