### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by djyde** [stickeroverflow/sticker-requests#11]
### 贴纸相关品牌

Rust

### 品牌授权方式

CC-BY-NC 4.0

https://www.rust-lang.org/en-US/legal.html

### 贴纸素材

![](https://www.rust-lang.org/logos/rust-logo-128x128-blk-v2.png)

**Comment by egoist** [comment]
cc @yetone

**Comment by yetone** [comment]
☆⌒(*＾-゜)v THX!!
