### ISSUE TITLE
[Request] Coverage 100% badge

### ISSUE THREAD

**Issue by feichao93** [stickeroverflow/sticker-requests#22]
测试覆盖率到达100%的徽章.

### 贴纸相关品牌

无品牌

### 品牌授权方式

应该不需要授权

### 贴纸素材

这两种style的比较适合作为贴纸.  下面的图有点小, 可以点进去把SVG放大了看

![img](https://img.shields.io/badge/coverage-100%25-green.svg?style=flat-square)

![img](https://img.shields.io/badge/coverage-100%25-green.svg?style=flat)

上面两个徽章来自 http://shields.io/

**Comment by egoist** [comment]
lol 我觉得也需要 build *passing* 的贴纸

**Comment by feichao93** [comment]
给人一种很可靠的感觉
