### ISSUE TITLE
对几个 licenses 的疑问

### ISSUE THREAD

**Issue by justjavac** [stickeroverflow/sticker-requests#23]
看到你们的 sticker 计划我很感兴趣，而我也在制作一些开源的徽章 [justjavac/badge-store](https://github.com/justjavac/badge-store)，我在获取授权过程中，发现了一些和你们[许可列表](https://stickeroverflow.org/licenses/)不同的内容。

首先是 React：在 React 官网找不到任何关于 React Logo 的 license 信息，而你们的 LICENSE 则指向了一个第三方专门制作 svg 图片的网站。

Docker：你们执行了 Docker 的 License，然后就开始印刷了，但是在 License 中明确说明了禁止用在商业用途。https://github.com/justjavac/badge-store/issues/4

VS Code：No License，当没有 License 的时候，并不是意味着创作者放弃了权利。

希望以后在 License 的选取上更加谨慎一些。

**Comment by djyde** [comment]
感谢提醒，当时看 Node.js 的 Trademark Policy 有疏漏，刚刚再认真读了一下，确实好像不能使用。我已经发了邮件过去进一步询问，如果确实不允许，我们立刻下架。（Docker 同理）

关于 React 的 logo. 当时我也很疑惑，官方并没有指明任何 License. 所以我在第三方制作 svg 的网站里找，看到该网站对 svg 的许可协议，我的理解是只需要遵守这个网站的协议即可。不知道这个理解正不正确，我们可以一起讨论，如果不正确，也会立刻下架。

justjavac/badge-store 是个好项目，我们愿意一起维护一个 trademark 协议列表，也很愿意一起研究许可的问题。

再次感谢提醒。

**Comment by justjavac** [comment]
我看了那个网站，还有 QQ、微信、……的 logo
