### ISSUE TITLE
[Request] Vim

### ISSUE THREAD

**Issue by cosmtrek** [stickeroverflow/sticker-requests#24]
### 贴纸相关品牌

Vim

### 品牌授权方式

GPL-compatible

### 贴纸素材

https://vim.sourceforge.io/logos.php

**Comment by leoprc** [comment]
我也想要这个，同支持

**Comment by fmfsaisai** [comment]
同求

**Comment by rfyiamcool** [comment]
+1

**Comment by youkpter** [comment]
+1

**Comment by djyde** [comment]
已经上架 https://stickeroverflow.xyz/blog/2019-03-new-sticker/
