### ISSUE TITLE
某宝店铺没有商品

### ISSUE THREAD

**Issue by elliothux** [stickeroverflow/sticker-requests#29]
还有另外的购买渠道吗？

**Comment by igigi** [comment]
您可以去[这个网站](https://www.smallsticker.com)购买

**Comment by MarcSteven** [comment]
Perhaps the shop was closed,so cannot visit it again.it's a pity to miss it .

**Comment by djyde** [comment]
现在可以在微店购买 http://weidian.com/item.html?itemID=2719185809
