### ISSUE TITLE
[Request] Golang

### ISSUE THREAD

**Issue by xuzhenglun** [stickeroverflow/sticker-requests#4]
### 贴纸相关品牌

Golang

### 品牌授权方式

The gopher images are Creative Commons Attributions 3.0 licensed. That means you can play with the images but you must give credit to their creator (Renee French) wherever they are used.

### 贴纸素材

https://golang.org/doc/gopher/

**Comment by djyde** [comment]
License 地址 https://golang.org/doc/gopher/README

**Comment by djyde** [comment]
duplicated #12
