### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by djyde** [stickeroverflow/sticker-requests#8]
### 贴纸相关品牌

Node.js

### 品牌授权方式

https://nodejs.org/static/documents/trademark-policy.pdf

>  You may create things with the marks for your own use. These can be t-shirts, caps, desktop wallpapers, and even cakes! But please make sure that your design follows the Visual Identity Guidelines. Keep in mind that you are not allowed to sell branded items with the Node.js marks except as explained in the next paragraph.

### 贴纸素材

https://nodejs.org/en/about/resources/

**Comment by justjavac** [comment]
> Keep in mind that you are **not allowed** to sell branded items with the Node.js marks except as explained in the next paragraph.

这是可以还是不可以？
